Reproducing previewProps missing
How to reproduce:
npm run install
npm run preview
localhost:3000/api/draft?secret=secret-token&slug=preview-page

Gives:
Error: Invariant: previewProps missing previewModeId this should never happen

This repo (except this last commit) comes from this rather similar, but fixed, issue: https://github.com/vercel/next.js/issues/67075

The error is thrown in Nextjs from this line:
https://github.com/vercel/next.js/blob/c839d589abf95d248398848081b8194e0d3aed5c/packages/next/src/server/async-storage/draft-mode-provider.ts#L52
Either because:
- "this" is not defined here
- "this._previewModeId" is not defined here

Running npm run dev and hitting localhost:3000/api/draft?secret=secret-token&slug=preview-page doesn't fail.

The middleware.ts file in this repo is irrellevant but I left it as is.